const fs = require('node:fs')
const path = require('node:path')
const { execFileSync } = require('node:child_process')
const root = path.resolve(__dirname, '..')
process.chdir(root)
execFileSync(process.execPath, ['scripts/mam.cjs'], { stdio:'inherit' })
const dest = path.join(root, 'dist/student')
fs.mkdirSync(dest, {recursive:true})
for (const file of ['web.js','web.css']) fs.copyFileSync('attendpro/student/-/'+file, dest+'/'+file)
for (const file of ['index.html','manifest.webmanifest','icon.svg','icon-192.png','icon-512.png']) fs.copyFileSync('attendpro/student/'+file, dest+'/'+file)
fs.copyFileSync('assets/sw.js', dest+'/sw.js')
fs.writeFileSync(dest+'/bridge.js', '// Native BLE bridge is included only in the Capacitor build.\n')
fs.mkdirSync('shell/www', {recursive:true})
fs.cpSync(dest, 'shell/www', {recursive:true})
require('../shell/node_modules/esbuild').buildSync({entryPoints:['shell/bridge.js'],bundle:true,format:'iife',outfile:'shell/www/bridge.js'})
